server:
  port: 8888

spring:
  application:
    name: spring-config-deep
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:${HOME}/projects/test_projects/boowalla/spring-config-deep/api-config-values/